{
    'name': 'HUE OpenEduCat Customization',
    'version': '17.0.1.0',
    'license': 'LGPL-3',
    'category': 'Education',
    "sequence": 3,
    'summary': 'Adding Horus customization to OpenEduCat',
    'complexity': "easy",
    'author': 'HUE',
    
    'depends': ['base','openeducat_core','openeducat_facility', 'openeducat_classroom'],
    
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/academic_year.xml',
        'views/financial_year.xml',
        'views/installment.xml',
        'views/city.xml',
        'views/faculty.xml',
        'views/join_year.xml',
        'views/level.xml',
        'views/term.xml',
        'views/semester.xml',
        'views/course.xml',
        'views/batch.xml',
        'views/grade.xml',
        'views/assessment.xml',
        'views/custom_student.xml',
        'views/block_reason.xml',
        'views/grade_equivalent.xml',
        'views/discount.xml',
        'views/certificate.xml',
        'views/nationality.xml',
        'views/professor.xml',
        'views/student_status.xml',
        'views/subject.xml',
        # 'views/classroom.xml',
        'views/timing_gap.xml',
        'views/facility.xml',
        'views/section.xml',
        'views/custom_fees_terms.xml',
        'menus/op_menu.xml',
        'menus/migration_menu.xml',
    ],
    # 'post_init_hook': 'post_init_hook',
    "assets": {
        "web.assets_backend": {
            "HUE_openeducat_core/static/src/css/style.css",
        }
    },
    'installable': True,
    'auto_install': False,
    'application': True,
}
