{
    'name': 'HUE questionnaire',
    'version': '17.0.1.0',
    'license': 'LGPL-3',
    'category': 'Education',
    "sequence": 2,
    'summary': 'Horus questionnaire',
    'complexity': "easy",
    'author': 'HUE',
    'depends': ['base','openeducat_core', 'survey', 'openeducat_timetable', 'hue_timetable'],
    'data': [
        'views/question_types.xml',
        'views/questions.xml',
        'views/questionnaire_instructors.xml',
        'views/students_questionnaire_answers.xml',
        'views/questionnaire_instructor_answers.xml',
        'views/questionnaire_service_answers.xml',
        'views/students_questionnaire.xml',
        'views/hue_questionnaire.xml',
        'menus/questionnaire_menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
